# Generated by Django 3.0.8 on 2020-07-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegenotice', '0002_auto_20200731_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
    ]
