# Generated by Django 3.0.8 on 2020-08-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegenotice', '0003_auto_20200731_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegenotice.branch'),
        ),
    ]
