# Generated by Django 3.0.8 on 2020-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegenotice', '0004_auto_20200801_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='msg',
            field=models.TextField(max_length=1000),
        ),
    ]
