# Generated by Django 3.0.8 on 2020-08-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegenotice', '0005_auto_20200802_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hod',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegenotice.branch')),
            ],
        ),
    ]
