# Generated by Django 3.0.8 on 2020-08-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegenotice', '0007_auto_20200802_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
